# Generated by Django 5.2 on 2026-09-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day", models.DateField()),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("route_detail_view", "Route-detail view"),
                            ("gpx_download_click", "GPX download click"),
                            ("original_source_click", "Original-source click"),
                        ],
                        max_length=32,
                    ),
                ),
                ("count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ["-day", "event"],
                "indexes": [
                    models.Index(
                        fields=["event", "day"], name="analytics_event_day_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "event"), name="analytics_day_event_unique"
                    )
                ],
            },
        ),
    ]
