# Generated by Django 5.2.17 on 2026-09-20 12:49

import apps.accounts.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(max_length=40)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_athlete_id', models.PositiveBigIntegerField(unique=True)),
                ('strava_display_name', models.CharField(blank=True, max_length=240)),
                ('strava_profile_image_url', models.URLField(blank=True, max_length=500)),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('lifecycle', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('pending-deletion', 'Pending deletion'), ('deleted', 'Deleted')], default='connected', max_length=24)),
                ('deletion_deadline', models.DateTimeField(blank=True, null=True)),
                ('session_epoch', models.PositiveBigIntegerField(default=0)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PlayerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', apps.accounts.fields.EncryptedSecretField()),
                ('refresh_token', apps.accounts.fields.EncryptedSecretField()),
                ('expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='accounts.player')),
            ],
        ),
    ]
