# Generated by Django 5.2.17 on 2026-09-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_lifecycle_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdeletiontombstone',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed')], default='completed', editable=False, max_length=16),
        ),
    ]
