# Generated by Django 5.2.17 on 2026-09-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_identity_guard"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playeridentityguard",
            index=models.Index(fields=["invalidated_at"], name="accounts_pl_invalid_7ade8a_idx"),
        ),
    ]
