# Generated by Django 5.2.17 on 2026-09-21 14:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identity_guard_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('invite_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_competitions', to='accounts.player')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='active_competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_players', to='accounts.competition'),
        ),
        migrations.CreateModel(
            name='ImportedActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_activity_id', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_activities', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('computed_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='accounts.player')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_results', to='accounts.importedactivity')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_memberships', to='accounts.player')),
            ],
            options={
                'ordering': ('joined_at', 'pk'),
                'indexes': [models.Index(fields=['player', 'competition'], name='accounts_co_player__41ebe5_idx')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'player'), name='accounts_competition_member_unique')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRecomputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveBigIntegerField()),
                ('affected_player_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomputations', to='accounts.competition')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_co_status_19f83d_idx')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'generation'), name='accounts_competition_generation_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='importedactivity',
            index=models.Index(fields=['player', 'imported_at'], name='accounts_im_player__21034b_idx'),
        ),
        migrations.AddConstraint(
            model_name='importedactivity',
            constraint=models.UniqueConstraint(fields=('player', 'provider_activity_id'), name='accounts_player_activity_unique'),
        ),
        migrations.AddIndex(
            model_name='competitionresult',
            index=models.Index(fields=['competition', 'player'], name='accounts_co_competi_8aed84_idx'),
        ),
        migrations.AddConstraint(
            model_name='competitionresult',
            constraint=models.UniqueConstraint(fields=('competition', 'player', 'activity'), name='accounts_competition_result_unique'),
        ),
    ]
