# Generated by Django 5.2.17 on 2026-09-21 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_competition_player_active_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionrecomputation',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitionrecomputation',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionrecomputation',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
