# Generated by Django 5.2.17 on 2026-09-25 07:10

import apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_stravasyncjob_dispatch_leases'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaQuotaState',
            fields=[
                ('key', models.CharField(default='global', max_length=32, primary_key=True, serialize=False)),
                ('short_window_used', models.PositiveIntegerField(default=0)),
                ('daily_used', models.PositiveIntegerField(default=0)),
                ('short_window_limit', models.PositiveIntegerField(default=100)),
                ('daily_limit', models.PositiveIntegerField(default=1000)),
                ('short_window_reset_at', models.DateTimeField(blank=True, null=True)),
                ('daily_reset_at', models.DateTimeField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('in_flight', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='stravasyncjob',
            name='retryable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='expires_at',
            field=models.DateTimeField(default=apps.accounts.models.webhook_event_expiry),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strava_webhook_events', to='accounts.player'),
        ),
    ]
