# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.catalogue.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_stravasyncjob_dispatch_leases"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                ("algorithm_version", models.CharField(max_length=64)),
                ("input_digest", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("fresh", "Fresh"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("trace_count", models.PositiveIntegerField(default=0)),
                ("coordinate_count", models.PositiveIntegerField(default=0)),
                ("face_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=240)),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_calculations",
                        to="accounts.competition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("face_id", models.PositiveIntegerField()),
                (
                    "geometry",
                    apps.catalogue.fields.RoutePolygonField(srid=4326, spatial_index=True),
                ),
                ("area_m2", models.DecimalField(decimal_places=3, max_digits=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="accounts.capturecalculation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaptureFaceOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("shared_area_m2", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "face",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="accounts.captureface",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_face_ownerships",
                        to="accounts.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CapturePlayerArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owned_area_m2", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_areas",
                        to="accounts.capturecalculation",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_areas",
                        to="accounts.player",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="capturecalculation",
            index=models.Index(fields=["competition", "status"], name="accounts_ca_competi_32a5ca_idx"),
        ),
        migrations.AddIndex(
            model_name="captureface",
            index=models.Index(
                fields=["calculation", "effective_date"], name="accounts_ca_calcula_5003cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capturefaceowner",
            index=models.Index(fields=["player", "face"], name="accounts_ca_player__24677a_idx"),
        ),
        migrations.AddIndex(
            model_name="captureplayerarea",
            index=models.Index(
                fields=["player", "calculation"], name="accounts_ca_player__e08399_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturecalculation",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_current=True),
                fields=("competition",),
                name="accounts_capture_calculation_one_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="capturecalculation",
            constraint=models.UniqueConstraint(
                fields=("competition", "generation"),
                name="accounts_capture_calculation_generation_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="captureface",
            constraint=models.UniqueConstraint(
                fields=("calculation", "face_id"), name="accounts_capture_face_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="capturefaceowner",
            constraint=models.UniqueConstraint(
                fields=("face", "player"), name="accounts_capture_face_owner_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="captureplayerarea",
            constraint=models.UniqueConstraint(
                fields=("calculation", "player"), name="accounts_capture_player_area_unique"
            ),
        ),
    ]
