# Generated by Django 5.2.17 on 2026-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_stravaquotastate_stravasyncjob_retryable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaquotastate',
            name='read_daily_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='stravaquotastate',
            name='read_daily_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stravaquotastate',
            name='read_short_window_limit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='stravaquotastate',
            name='read_short_window_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StravaQuotaReservation',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'released_at'], name='accounts_st_expires_65cfd1_idx')],
            },
        ),
    ]
