# Generated by Django 5.2 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_stravaquotastate_read_daily_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionmembership",
            name="sharing_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competitionmembership",
            name="sharing_scope",
            field=models.CharField(
                choices=[
                    ("none", "No sharing"),
                    ("recent", "Recent history"),
                    ("full_history", "Full available history"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
