# Generated by Django 5.2 on 2026-09-25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_competitionmembership_sharing_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionmembership",
            name="sharing_disclosure_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name="CompetitionSharingConsentAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("granted", "Granted"), ("withdrawn", "Withdrawn")],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("none", "No sharing"),
                            ("recent", "Recent history"),
                            ("full_history", "Full available history"),
                        ],
                        max_length=16,
                    ),
                ),
                ("disclosure_version", models.CharField(max_length=32)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_audits",
                        to="accounts.competitionmembership",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["membership", "recorded_at"],
                        name="accounts_co_members_31d118_idx",
                    )
                ],
            },
        ),
    ]
