# Generated by Django 5.2.17 on 2026-09-24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_capture_calculation_captureface_capturefaceowner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturecalculation",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="capturecalculation",
            name="lease_token",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="capturecalculation",
            name="lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capturecalculation",
            name="next_attempt_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
