# Generated by Django 5.2.17 on 2026-09-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_capturecalculation_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturefaceowner',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_face_ownerships', to='accounts.player'),
        ),
        migrations.AlterField(
            model_name='captureplayerarea',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_areas', to='accounts.player'),
        ),
    ]
