# Generated by Django 5.2.17 on 2026-09-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_preserve_capture_evidence_on_player_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='capture_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
