# Generated by Django 5.2.17 on 2026-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_capture_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionrecomputation',
            name='capture_generation',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
