# Generated by Django 5.2.17 on 2026-09-27 04:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_capturecalculation_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='strava_athlete_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('accepted_files', models.PositiveIntegerField(default=0)),
                ('duplicate_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('attested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=240)),
                ('content_sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('duplicate', 'Duplicate'), ('unsupported', 'Unsupported'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('error_detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_files', to='accounts.importedactivity')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='accounts.activityuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'status'], name='accounts_ac_batch_i_4ca17b_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'original_name', 'content_sha256'), name='accounts_upload_file_unique')],
            },
        ),
        migrations.CreateModel(
            name='CompetitionInviteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_digest', models.CharField(max_length=64)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_redemptions', to='accounts.competition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_redemptions', to='accounts.player')),
            ],
            options={
                'indexes': [models.Index(fields=['competition', 'code_digest'], name='accounts_co_competi_55dcec_idx')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'player'), name='accounts_invite_redemption_unique')],
            },
        ),
    ]
