# Generated by Django 5.2.17 on 2026-09-21 21:08

import apps.catalogue.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_stravasyncjob_dispatch_leases'),
        ('reference_routes', '0004_reference_alteration_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('player', 'Player'), ('competition', 'Competition')], max_length=16)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('tolerance_meters', models.DecimalField(decimal_places=3, default=50, max_digits=8)),
                ('total_length_meters', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('covered_length_meters', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('completion_percent', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('algorithm_version', models.CharField(default='corridor-v1', max_length=32)),
                ('route_checksum', models.CharField(blank=True, max_length=64)),
                ('membership_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evidence_digest', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_completions', to='accounts.competition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_completions', to='accounts.player')),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_results', to='reference_routes.referencerouteversion')),
            ],
        ),
        migrations.CreateModel(
            name='RouteCompletionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_activity_id', models.CharField(max_length=80)),
                ('activity_player_id', models.PositiveBigIntegerField()),
                ('covered_length_meters', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('covered_geometry', apps.catalogue.fields.RouteGeometryField(blank=True, null=True)),
                ('activity_geometry_hash', models.CharField(blank=True, max_length=64)),
                ('membership_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_completion_evidence', to='accounts.importedactivity')),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reference_routes.routecompletion')),
            ],
        ),
        migrations.CreateModel(
            name='RouteCompletionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('subject_type', models.CharField(choices=[('player', 'Player'), ('competition', 'Competition')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.competition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_jobs', to='reference_routes.referencerouteversion')),
            ],
        ),
        migrations.CreateModel(
            name='RouteCompletionMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('player', 'Player'), ('competition', 'Competition')], max_length=16)),
                ('month', models.DateField()),
                ('covered_length_meters', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('covered_geometry', apps.catalogue.fields.RouteGeometryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_route_completions', to='accounts.competition')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_route_completions', to='accounts.player')),
                ('route_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_completions', to='reference_routes.referencerouteversion')),
            ],
        ),
        migrations.AddIndex(
            model_name='routecompletion',
            index=models.Index(fields=['status', 'requested_at'], name='completion_status_req_idx'),
        ),
        migrations.AddIndex(
            model_name='routecompletion',
            index=models.Index(fields=['route_version', 'subject_type'], name='completion_version_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='routecompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('route_version', 'player'), name='completion_route_player_unique'),
        ),
        migrations.AddConstraint(
            model_name='routecompletion',
            constraint=models.UniqueConstraint(condition=models.Q(('competition__isnull', False)), fields=('route_version', 'competition'), name='completion_route_competition_unique'),
        ),
        migrations.AddConstraint(
            model_name='routecompletion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', True), ('player__isnull', False), ('subject_type', 'player')), models.Q(('competition__isnull', False), ('player__isnull', True), ('subject_type', 'competition')), _connector='OR'), name='completion_subject_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='routecompletionevidence',
            constraint=models.UniqueConstraint(fields=('completion', 'provider_activity_id'), name='completion_evidence_activity_unique'),
        ),
        migrations.AddIndex(
            model_name='routecompletionjob',
            index=models.Index(fields=['status', 'next_attempt_at'], name='completion_job_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='routecompletionmonthly',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('route_version', 'player', 'month'), name='completion_month_player_unique'),
        ),
        migrations.AddConstraint(
            model_name='routecompletionmonthly',
            constraint=models.UniqueConstraint(condition=models.Q(('competition__isnull', False)), fields=('route_version', 'competition', 'month'), name='completion_month_competition_unique'),
        ),
    ]
