# Generated by Django 5.2.17 on 2026-09-22 04:27

import apps.catalogue.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_stravasyncjob_dispatch_leases'),
        ('reference_routes', '0005_routecompletion_routecompletionevidence_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='routecompletionevidence',
            name='completion_evidence_activity_unique',
        ),
        migrations.AddField(
            model_name='routecompletion',
            name='evidence_generation',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='routecompletionevidence',
            name='evidence_generation',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='routecompletionjob',
            name='dispatch_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routecompletionjob',
            name='dispatch_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='routecompletionjob',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routecompletionevidence',
            name='covered_geometry',
            field=apps.catalogue.fields.RouteCoverageGeometryField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='routecompletionevidence',
            constraint=models.UniqueConstraint(fields=('completion', 'evidence_generation', 'provider_activity_id'), name='completion_evidence_activity_unique'),
        ),
    ]
