# Generated by Django 5.2.17 on 2026-09-22 04:56

from django.db import migrations

import apps.catalogue.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "reference_routes",
            "0006_remove_routecompletionevidence_completion_evidence_activity_unique_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="routecompletionmonthly",
            name="covered_geometry",
            field=apps.catalogue.fields.RouteCoverageGeometryField(blank=True, null=True),
        ),
    ]
