# Generated by Django 5.2.17 on 2026-09-23

import apps.catalogue.fields
from django.db import migrations


def backfill_covered_geometry(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    RouteCompletion = apps.get_model("reference_routes", "RouteCompletion")
    RouteCompletionEvidence = apps.get_model("reference_routes", "RouteCompletionEvidence")
    for completion in RouteCompletion.objects.filter(
        status="fresh", covered_geometry__isnull=True
    ).iterator(chunk_size=100):
        aggregate = None
        evidence = RouteCompletionEvidence.objects.filter(
            completion_id=completion.pk,
            evidence_generation=completion.evidence_generation,
        ).exclude(covered_geometry__isnull=True)
        for geometry in evidence.values_list("covered_geometry", flat=True).iterator(chunk_size=100):
            aggregate = geometry.clone() if aggregate is None else aggregate.union(geometry)
        if aggregate is not None and not aggregate.empty:
            RouteCompletion.objects.filter(pk=completion.pk).update(covered_geometry=aggregate)


class Migration(migrations.Migration):
    dependencies = [
        (
            "reference_routes",
            "0007_alter_routecompletionmonthly_covered_geometry",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="routecompletion",
            name="covered_geometry",
            field=apps.catalogue.fields.RouteCoverageGeometryField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_covered_geometry, migrations.RunPython.noop),
    ]
