# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_routes", "0008_routecompletion_covered_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routecompletionjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
