# Generated by Django 5.2.17 on 2026-09-04 11:09

import apps.catalogue.fields
import apps.catalogue.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_catalogue_database_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE TRIGGER catalogue_route_approved_guard_insert
                BEFORE INSERT ON catalogue_route
                WHEN NEW.current_approved_version_id IS NOT NULL
                 AND NOT EXISTS (
                    SELECT 1
                    FROM catalogue_routeversion version
                    JOIN catalogue_routesource source ON source.id = version.source_id
                    WHERE version.id = NEW.current_approved_version_id
                      AND source.route_id = NEW.id
                      AND version.technical_status = 'valid'
                )
                BEGIN SELECT RAISE(ABORT, 'approved route version must belong to this route and be valid'); END;
                """
            )
            cursor.execute(
                """
                CREATE TRIGGER catalogue_route_approved_guard_update
                BEFORE UPDATE ON catalogue_route
                WHEN NEW.current_approved_version_id IS NOT NULL
                 AND NOT EXISTS (
                    SELECT 1
                    FROM catalogue_routeversion version
                    JOIN catalogue_routesource source ON source.id = version.source_id
                    WHERE version.id = NEW.current_approved_version_id
                      AND source.route_id = NEW.id
                      AND version.technical_status = 'valid'
                )
                BEGIN SELECT RAISE(ABORT, 'approved route version must belong to this route and be valid'); END;
                """
            )
            cursor.execute(
                """
                CREATE TRIGGER catalogue_route_version_guard
                BEFORE UPDATE ON catalogue_routeversion
                WHEN NEW.source_id IS NOT OLD.source_id
                  OR NEW.version_number IS NOT OLD.version_number
                  OR NEW.checksum IS NOT OLD.checksum
                  OR NEW.normalized_geometry IS NOT OLD.normalized_geometry
                  OR NEW.simplified_geometry IS NOT OLD.simplified_geometry
                  OR NEW.distance_m IS NOT OLD.distance_m
                  OR NEW.ascent_m IS NOT OLD.ascent_m
                  OR NEW.descent_m IS NOT OLD.descent_m
                  OR NEW.loop_status IS NOT OLD.loop_status
                  OR NEW.technical_status IS NOT OLD.technical_status
                  OR NEW.validation_error IS NOT OLD.validation_error
                  OR NEW.created_at IS NOT OLD.created_at
                  OR (
                      NEW.approved_at IS NOT OLD.approved_at
                      AND NOT (
                          OLD.approved_at IS NULL
                          AND NEW.approved_at IS NOT NULL
                      )
                  )
                  OR (
                      NOT (
                          OLD.payload_removed_at IS NULL
                          AND NEW.payload_removed_at IS NOT NULL
                          AND OLD.original_gpx_storage_key != ''
                          AND NEW.original_gpx_storage_key = ''
                          AND NEW.payload_removal_reason != ''
                      )
                      AND (
                          NEW.original_gpx_storage_key IS NOT OLD.original_gpx_storage_key
                          OR NEW.payload_removed_at IS NOT OLD.payload_removed_at
                          OR NEW.payload_removal_reason IS NOT OLD.payload_removal_reason
                      )
                  )
                BEGIN SELECT RAISE(ABORT, 'historical route version content is immutable'); END;
                """
            )
            cursor.execute(
                """
                CREATE TRIGGER catalogue_route_version_no_delete
                BEFORE DELETE ON catalogue_routeversion
                BEGIN SELECT RAISE(ABORT, 'historical route versions cannot be deleted'); END;
                """
            )
            cursor.execute(
                """
                CREATE TRIGGER catalogue_route_source_guard
                BEFORE UPDATE ON catalogue_routesource
                WHEN NEW.route_id IS NOT OLD.route_id OR NEW.mapy_url IS NOT OLD.mapy_url
                BEGIN SELECT RAISE(ABORT, 'route source identity is immutable'); END;
                """
            )
        return
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION catalogue_route_version_guard()
            RETURNS trigger LANGUAGE plpgsql AS $guard$
            BEGIN
                IF NEW.source_id IS DISTINCT FROM OLD.source_id
                   OR NEW.version_number IS DISTINCT FROM OLD.version_number
                   OR NEW.checksum IS DISTINCT FROM OLD.checksum
                   OR NEW.normalized_geometry IS DISTINCT FROM OLD.normalized_geometry
                   OR NEW.simplified_geometry IS DISTINCT FROM OLD.simplified_geometry
                   OR NEW.distance_m IS DISTINCT FROM OLD.distance_m
                   OR NEW.ascent_m IS DISTINCT FROM OLD.ascent_m
                   OR NEW.descent_m IS DISTINCT FROM OLD.descent_m
                   OR NEW.loop_status IS DISTINCT FROM OLD.loop_status
                   OR NEW.technical_status IS DISTINCT FROM OLD.technical_status
                   OR NEW.validation_error IS DISTINCT FROM OLD.validation_error
                   OR NEW.created_at IS DISTINCT FROM OLD.created_at
                   OR (
                       NEW.approved_at IS DISTINCT FROM OLD.approved_at
                       AND NOT (
                           OLD.approved_at IS NULL
                           AND NEW.approved_at IS NOT NULL
                       )
                   )
                THEN
                    RAISE EXCEPTION 'historical route version content is immutable';
                END IF;
                IF NOT (
                       OLD.payload_removed_at IS NULL
                       AND NEW.payload_removed_at IS NOT NULL
                       AND OLD.original_gpx_storage_key <> ''
                       AND NEW.original_gpx_storage_key = ''
                       AND NEW.payload_removal_reason <> ''
                   )
                   AND (
                       NEW.original_gpx_storage_key IS DISTINCT FROM OLD.original_gpx_storage_key
                       OR NEW.payload_removed_at IS DISTINCT FROM OLD.payload_removed_at
                       OR NEW.payload_removal_reason IS DISTINCT FROM OLD.payload_removal_reason
                   )
                THEN
                    RAISE EXCEPTION 'route version payload removal metadata is immutable except removal';
                END IF;
                RETURN NEW;
            END;
            $guard$;
            """
        )
        cursor.execute(
            "DROP TRIGGER IF EXISTS catalogue_route_version_guard_trigger "
            "ON catalogue_routeversion"
        )
        cursor.execute(
            "CREATE TRIGGER catalogue_route_version_guard_trigger "
            "BEFORE UPDATE ON catalogue_routeversion FOR EACH ROW "
            "EXECUTE FUNCTION catalogue_route_version_guard()"
        )
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION catalogue_route_source_guard()
            RETURNS trigger LANGUAGE plpgsql AS $guard$
            BEGIN
                IF NEW.route_id IS DISTINCT FROM OLD.route_id
                   OR NEW.mapy_url IS DISTINCT FROM OLD.mapy_url
                THEN
                    RAISE EXCEPTION 'route source identity is immutable';
                END IF;
                RETURN NEW;
            END;
            $guard$;
            """
        )
        cursor.execute(
            "DROP TRIGGER IF EXISTS catalogue_route_source_guard_trigger ON catalogue_routesource"
        )
        cursor.execute(
            "CREATE TRIGGER catalogue_route_source_guard_trigger "
            "BEFORE UPDATE ON catalogue_routesource FOR EACH ROW "
            "EXECUTE FUNCTION catalogue_route_source_guard()"
        )
        cursor.execute(
            "CREATE OR REPLACE FUNCTION catalogue_route_version_no_delete() "
            "RETURNS trigger LANGUAGE plpgsql AS $guard$ "
            "BEGIN RAISE EXCEPTION 'historical route versions cannot be deleted'; END; "
            "$guard$"
        )
        cursor.execute(
            "DROP TRIGGER IF EXISTS catalogue_route_version_no_delete_trigger ON catalogue_routeversion"
        )
        cursor.execute(
            "CREATE TRIGGER catalogue_route_version_no_delete_trigger "
            "BEFORE DELETE ON catalogue_routeversion FOR EACH ROW "
            "EXECUTE FUNCTION catalogue_route_version_no_delete()"
        )
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION catalogue_route_approved_guard()
            RETURNS trigger LANGUAGE plpgsql AS $guard$
            BEGIN
                IF NEW.current_approved_version_id IS NOT NULL AND NOT EXISTS (
                    SELECT 1
                    FROM catalogue_routeversion version
                    JOIN catalogue_routesource source ON source.id = version.source_id
                    WHERE version.id = NEW.current_approved_version_id
                      AND source.route_id = NEW.id
                      AND version.technical_status = 'valid'
                ) THEN
                    RAISE EXCEPTION 'approved route version must belong to this route and be valid';
                END IF;
                RETURN NEW;
            END;
            $guard$;
            """
        )
        cursor.execute(
            "DROP TRIGGER IF EXISTS catalogue_route_approved_guard_trigger ON catalogue_route"
        )
        cursor.execute(
            "CREATE TRIGGER catalogue_route_approved_guard_trigger "
            "BEFORE INSERT OR UPDATE ON catalogue_route FOR EACH ROW "
            "EXECUTE FUNCTION catalogue_route_approved_guard()"
        )


def drop_catalogue_database_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_approved_guard_insert")
            cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_approved_guard_update")
            cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_version_guard")
            cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_version_no_delete")
            cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_source_guard")
        return
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_version_guard_trigger ON catalogue_routeversion")
        cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_version_no_delete_trigger ON catalogue_routeversion")
        cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_source_guard_trigger ON catalogue_routesource")
        cursor.execute("DROP TRIGGER IF EXISTS catalogue_route_approved_guard_trigger ON catalogue_route")
        cursor.execute("DROP FUNCTION IF EXISTS catalogue_route_version_guard()")
        cursor.execute("DROP FUNCTION IF EXISTS catalogue_route_version_no_delete()")
        cursor.execute("DROP FUNCTION IF EXISTS catalogue_route_source_guard()")
        cursor.execute("DROP FUNCTION IF EXISTS catalogue_route_approved_guard()")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default=apps.catalogue.models._default_route_slug, max_length=180, unique=True)),
                ('lifecycle', models.CharField(choices=[('published', 'Published'), ('quarantined', 'Quarantined'), ('soft_deleted', 'Soft deleted')], default='published', max_length=20)),
                ('original_source_title', models.CharField(blank=True, max_length=500)),
                ('thread_title', models.CharField(blank=True, max_length=500)),
                ('generated_title', models.CharField(blank=True, max_length=500)),
                ('display_title', models.CharField(blank=True, max_length=500)),
                ('admin_title_override', models.CharField(blank=True, max_length=500)),
                ('title_provenance', models.CharField(choices=[('geographic', 'Thread and geographic context'), ('author_date', 'Thread, author, and post date'), ('route_id', 'Thread and stable route ID'), ('admin_override', 'Administrator override')], default='route_id', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ForumAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('profile_url', models.URLField(blank=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['username', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='catalogue_author_external_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='catalogue_thread_external_id_unique')],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(unique=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='catalogue.forumauthor')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='catalogue.forumthread')),
            ],
            options={
                'ordering': ['posted_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RouteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_category_assignments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_links', to='catalogue.category')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='catalogue.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapy_url', models.URLField(max_length=1000, unique=True)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('processing_status', models.CharField(choices=[('discovered', 'Discovered'), ('processing', 'Processing'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='discovered', max_length=20)),
                ('source_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='catalogue.route')),
            ],
            options={
                'ordering': ['-discovered_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RouteSourcePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='catalogue.forumpost')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_links', to='catalogue.routesource')),
            ],
        ),
        migrations.AddField(
            model_name='routesource',
            name='posts',
            field=models.ManyToManyField(related_name='route_sources', through='catalogue.RouteSourcePost', to='catalogue.forumpost'),
        ),
        migrations.CreateModel(
            name='RouteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('original_gpx_storage_key', models.CharField(blank=True, max_length=1000)),
                ('payload_removed_at', models.DateTimeField(blank=True, null=True)),
                ('payload_removal_reason', models.TextField(blank=True)),
                ('normalized_geometry', apps.catalogue.fields.RouteGeometryField(blank=True, null=True)),
                ('simplified_geometry', apps.catalogue.fields.RouteGeometryField(blank=True, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ascent_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descent_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loop_status', models.CharField(choices=[('loop', 'Loop'), ('point_to_point', 'Point to point'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('technical_status', models.CharField(choices=[('discovered', 'Discovered'), ('processing', 'Processing'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='processing', max_length=20)),
                ('validation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalogue.routesource')),
            ],
            options={
                'ordering': ['source_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='PayloadDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key_snapshot', models.CharField(max_length=1000)),
                ('removal_reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payload_deletion_request', to='catalogue.routeversion')),
            ],
            options={
                'ordering': ['requested_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='catalogue_p_status_c893b0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='catalogue_payload_request_completed_timestamp')],
            },
        ),
        migrations.AddField(
            model_name='route',
            name='current_approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_for_routes', to='catalogue.routeversion'),
        ),
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('review', 'Reviewed'), ('publish', 'Published automatically'), ('keep_both', 'Keep both'), ('merge_sources', 'Merge sources'), ('quarantine', 'Quarantine'), ('restore', 'Restore'), ('remove', 'Remove')], max_length=30)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_moderation_decisions', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_decisions', to='catalogue.route')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_decisions', to='catalogue.routeversion')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('suspected_duplicate', 'Suspected duplicate'), ('variant', 'Variant')], max_length=30)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('route_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_a', to='catalogue.route')),
                ('route_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_b', to='catalogue.route')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDenylistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('denied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('route_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denylist_entries', to='catalogue.routesource')),
            ],
            options={
                'ordering': ['-denied_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='forumpost',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('thread', 'external_id'), name='catalogue_post_thread_external_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='routecategory',
            constraint=models.UniqueConstraint(fields=('route', 'category'), name='catalogue_route_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='routesourcepost',
            constraint=models.UniqueConstraint(fields=('source', 'post'), name='catalogue_source_post_unique'),
        ),
        migrations.AddIndex(
            model_name='routesource',
            index=models.Index(fields=['processing_status'], name='catalogue_source_process_idx'),
        ),
        migrations.AddIndex(
            model_name='routesource',
            index=models.Index(fields=['source_status'], name='catalogue_source_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='routeversion',
            constraint=models.UniqueConstraint(fields=('source', 'version_number'), name='catalogue_version_source_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='routeversion',
            constraint=models.UniqueConstraint(fields=('source', 'checksum'), name='catalogue_version_source_checksum_unique'),
        ),
        migrations.AddConstraint(
            model_name='routeversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gt', 0)), name='catalogue_version_positive_number'),
        ),
        migrations.AddConstraint(
            model_name='routeversion',
            constraint=models.CheckConstraint(condition=models.Q(('payload_removed_at__isnull', True), ('original_gpx_storage_key', ''), _connector='OR'), name='catalogue_removed_payload_has_no_storage_ref'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['lifecycle', 'updated_at'], name='catalogue_route_lifecycle_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['slug'], name='catalogue_route_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', False), ('lifecycle', 'soft_deleted')), models.Q(('lifecycle', 'soft_deleted'), _negated=True), _connector='OR'), name='catalogue_deleted_route_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lifecycle', 'quarantined'), _negated=True), ('quarantine_reason__gt', ''), _connector='OR'), name='catalogue_quarantined_route_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='similarityrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('route_a', models.F('route_b')), _negated=True), name='catalogue_similarity_no_self'),
        ),
        migrations.AddConstraint(
            model_name='similarityrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('similarity_score__isnull', True), models.Q(('similarity_score__gte', 0), ('similarity_score__lte', 1)), _connector='OR'), name='catalogue_similarity_score_range'),
        ),
        migrations.AddConstraint(
            model_name='similarityrelationship',
            constraint=models.UniqueConstraint(fields=('route_a', 'route_b'), name='catalogue_similarity_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='sourcedenylistentry',
            constraint=models.CheckConstraint(condition=models.Q(('active', True), ('restored_at__isnull', False), _connector='OR'), name='catalogue_restored_denylist_entry_has_timestamp'),
        ),
        migrations.RunPython(create_catalogue_database_guards, drop_catalogue_database_guards),
    ]
