# Generated by Django 5.2.17 on 2026-09-04 19:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSourceMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_source_merges', to=settings.AUTH_USER_MODEL)),
                ('canonical_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merged_source_links', to='catalogue.route')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_route_links', to='catalogue.routesource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canonical_route', 'source'), name='catalogue_source_merge_unique')],
            },
        ),
    ]
