# Generated by Django 5.2.17 on 2026-09-04 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_routesourcemerge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routesourcemerge',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routesourcemerge',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routesourcemerge',
            name='deactivated_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='routesourcemerge',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('source',), name='catalogue_active_source_merge_unique'),
        ),
    ]
