# Generated by Django 5.2.17 on 2026-09-04 20:44

import apps.catalogue.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_routesourcemerge_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHeatmapCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveSmallIntegerField()),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('boundary', apps.catalogue.fields.RoutePolygonField()),
                ('route_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zoom', 'y', 'x'],
                'indexes': [models.Index(fields=['zoom', 'route_count'], name='cat_heatmap_cell_count_idx')],
                'constraints': [models.UniqueConstraint(fields=('zoom', 'x', 'y'), name='catalogue_heatmap_cell_coordinates_unique')],
            },
        ),
        migrations.CreateModel(
            name='RouteBrowseGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.PositiveSmallIntegerField()),
                ('geometry', apps.catalogue.fields.RouteGeometryField()),
                ('tolerance_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browse_geometries', to='catalogue.routeversion')),
            ],
            options={
                'ordering': ['version_id', 'zoom'],
                'indexes': [models.Index(fields=['zoom', 'version'], name='cat_browse_geom_zoom_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'zoom'), name='catalogue_browse_geometry_version_zoom_unique'), models.CheckConstraint(condition=models.Q(('zoom__gte', 0)), name='catalogue_browse_geometry_zoom_positive')],
            },
        ),
        migrations.CreateModel(
            name='RouteHeatmapMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalogue.routeheatmapcell')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_memberships', to='catalogue.route')),
            ],
            options={
                'indexes': [models.Index(fields=['route', 'cell'], name='cat_heatmap_member_route_idx')],
                'constraints': [models.UniqueConstraint(fields=('cell', 'route'), name='catalogue_heatmap_membership_unique')],
            },
        ),
    ]
