# Generated by Django 5.2

from django.db import migrations, models


def add_profile_column(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        field_type = "text"
    else:
        field_type = "jsonb"
    table = schema_editor.quote_name("catalogue_routeversion")
    column = schema_editor.quote_name("elevation_profile")
    schema_editor.execute(
        f"ALTER TABLE {table} ADD COLUMN {column} {field_type} NOT NULL DEFAULT '[]'"
    )


def remove_profile_column(apps, schema_editor):
    table = schema_editor.quote_name("catalogue_routeversion")
    column = schema_editor.quote_name("elevation_profile")
    schema_editor.execute(f"ALTER TABLE {table} DROP COLUMN {column}")


class Migration(migrations.Migration):
    dependencies = [("catalogue", "0005_public_search_indexes")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(add_profile_column, remove_profile_column)],
            state_operations=[
                migrations.AddField(
                    model_name="routeversion",
                    name="elevation_profile",
                    field=models.JSONField(blank=True, default=list),
                )
            ],
        ),
    ]
