# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("catalogue", "0006_routeversion_elevation_profile")]

    operations = [
        migrations.AlterField(
            model_name="moderationdecision",
            name="action",
            field=models.CharField(
                choices=[
                    ("review", "Reviewed"),
                    ("publish", "Published automatically"),
                    ("select_version", "Selected approved version"),
                    ("keep_both", "Keep both"),
                    ("merge_sources", "Merge sources"),
                    ("quarantine", "Quarantine"),
                    ("restore", "Restore"),
                    ("remove", "Remove"),
                    ("source_unavailable", "Source unavailable"),
                    ("source_available", "Source available"),
                    ("denylist_restore", "Restore denylist entry"),
                    ("route_metadata", "Update route metadata"),
                    ("category_create", "Create category"),
                    ("category_update", "Update category"),
                    ("category_delete", "Delete category"),
                    ("category_assign", "Assign category"),
                    ("category_unassign", "Remove category"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="moderationdecision",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moderation_decisions",
                to="catalogue.route",
            ),
        ),
    ]
