# Generated by Django 5.2

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalogue", "0007_alter_moderationdecision_action"),
    ]
    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(choices=[("incorrect_route", "Incorrect route"), ("source_attribution", "Source or attribution"), ("author_removal", "Author removal"), ("rights_holder", "Rights-holder request"), ("other", "Other")], max_length=32)),
                ("message", models.TextField(max_length=5000)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("in_review", "In review"), ("accepted", "Accepted"), ("rejected", "Rejected"), ("duplicate", "Duplicate"), ("closed", "Closed")], default="pending", max_length=20)),
                ("decision", models.CharField(blank=True, choices=[("accept", "Accept"), ("reject", "Reject"), ("duplicate", "Mark duplicate"), ("close", "Close without action")], max_length=20)),
                ("decision_reason", models.TextField(blank=True)),
                ("duplicate_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("email_anonymized_at", models.DateTimeField(blank=True, null=True)),
                ("personal_details_anonymized_at", models.DateTimeField(blank=True, null=True)),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reports", to="catalogue.route")),
            ],
            options={
                "ordering": ["status", "-submitted_at", "-id"],
                "indexes": [
                    models.Index(fields=["route", "duplicate_fingerprint"], name="reports_route_fingerprint_idx"),
                    models.Index(fields=["status", "submitted_at"], name="reports_status_submitted_idx"),
                    models.Index(fields=["closed_at"], name="reports_closed_at_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReportAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="report_audit_events", to=settings.AUTH_USER_MODEL)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="audit_events", to="reports.report")),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
    ]
