# Generated by Django 5.2 on 2026-09-04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlCheckpoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stream", models.CharField(max_length=120, unique=True)),
                ("next_url", models.URLField(blank=True, max_length=1000)),
                ("page_number", models.PositiveIntegerField(default=0)),
                ("last_successful_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["stream"]},
        ),
        migrations.CreateModel(
            name="CrawlResponseCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=1000, unique=True)),
                ("final_url", models.URLField(blank=True, max_length=1000)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("body", models.TextField(blank=True)),
                ("etag", models.CharField(blank=True, max_length=500)),
                ("last_modified", models.CharField(blank=True, max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"indexes": [models.Index(fields=["fetched_at"], name="ingestion_c_fetched_6f7f6a_idx")]},
        ),
        migrations.CreateModel(
            name="CrawlTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("incremental", "Incremental"), ("backfill", "Historical backfill")], default="incremental", max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("paused", "Paused")], default="pending", max_length=20)),
                ("start_url", models.URLField(max_length=1000)),
                ("next_url", models.URLField(blank=True, max_length=1000)),
                ("max_pages", models.PositiveIntegerField(default=1)),
                ("pages_processed", models.PositiveIntegerField(default=0)),
                ("items_imported", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"indexes": [models.Index(fields=["status", "created_at"], name="ingestion_c_status_8db2dd_idx")]},
        ),
    ]
