# Generated by Django 5.2 on 2026-09-13

from datetime import timedelta

from django.db import migrations, models


BODY_RETENTION = timedelta(days=1)


def populate_body_expiry(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Give existing retained bodies the approved one-day expiry deadline."""

    del schema_editor
    cache_model = apps.get_model("ingestion", "CrawlResponseCache")
    pending = []
    for entry in cache_model.objects.filter(body__gt="", body_expires_at__isnull=True).iterator(
        chunk_size=1000
    ):
        entry.body_expires_at = entry.fetched_at + BODY_RETENTION
        pending.append(entry)
        if len(pending) >= 1000:
            cache_model.objects.bulk_update(pending, ["body_expires_at"])
            pending.clear()
    if pending:
        cache_model.objects.bulk_update(pending, ["body_expires_at"])


class Migration(migrations.Migration):
    dependencies = [("ingestion", "0009_orphan_reconciliation_cursor")]

    operations = [
        migrations.AddField(
            model_name="crawlresponsecache",
            name="body_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_body_expiry, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="crawlresponsecache",
            index=models.Index(
                condition=models.Q(body_expires_at__isnull=False),
                fields=["body_expires_at", "id"],
                name="ingestion_c_body_expiry_idx",
            ),
        ),
    ]
